# Generated by Django 5.2.8 on 2025-11-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='genres',
            new_name='add_genres',
        ),
        migrations.RenameField(
            model_name='add_genres',
            old_name='genres',
            new_name='genre',
        ),
    ]
