# Generated by Django 5.2.8 on 2025-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_genres_add_genres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=30)),
            ],
        ),
    ]
