# Generated by Django 5.2.8 on 2025-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='times',
            field=models.TimeField(max_length=30),
        ),
    ]
