# Generated by Django 5.2.8 on 2025-11-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_alter_timer_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='times',
            field=models.CharField(max_length=30),
        ),
    ]
