# Generated by Django 5.2.8 on 2025-11-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_alter_timer_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=30)),
            ],
        ),
    ]
