# Generated by Django 5.2.8 on 2025-11-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
