# Generated by Django 5.2.8 on 2025-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_add_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='theatres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='seats',
            old_name='theatre_name',
            new_name='rates',
        ),
    ]
