# Generated by Django 5.2.8 on 2025-11-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0011_theatres_rename_theatre_name_seats_rates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_movie',
            old_name='title',
            new_name='movie_name',
        ),
    ]
