# Generated by Django 5.2.8 on 2025-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0012_rename_title_add_movie_movie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('theatre', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('times', models.CharField(max_length=50)),
            ],
        ),
    ]
