# Generated by Django 5.2.8 on 2025-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_assign_theatre'),
    ]

    operations = [
        migrations.CreateModel(
            name='seat_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
            ],
        ),
    ]
