# Generated by Django 5.2.8 on 2025-11-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0014_seat_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_1', models.CharField(max_length=60)),
                ('actor_1_img', models.FileField(upload_to='file')),
                ('actor_2', models.CharField(max_length=60)),
                ('actor_2_img', models.FileField(upload_to='file')),
                ('actor_3', models.CharField(max_length=60)),
                ('actor_3_img', models.FileField(upload_to='file')),
                ('actor_4', models.CharField(max_length=60)),
                ('actor_4_img', models.FileField(upload_to='file')),
                ('actor_5', models.FileField(max_length=60, upload_to='')),
                ('actor_5_img', models.FileField(upload_to='file')),
                ('crew_1', models.CharField(max_length=60)),
                ('crew_1_desc', models.CharField(max_length=60)),
                ('crew_1_img', models.FileField(upload_to='file')),
                ('crew_2', models.CharField(max_length=60)),
                ('crew_2_desc', models.CharField(max_length=60)),
                ('crew_2_img', models.FileField(upload_to='file')),
                ('crew_3', models.CharField(max_length=60)),
                ('crew_3_desc', models.CharField(max_length=60)),
                ('crew_3_img', models.FileField(upload_to='file')),
                ('crew_4', models.CharField(max_length=60)),
                ('crew_4_desc', models.CharField(max_length=60)),
                ('crew_4_img', models.FileField(upload_to='file')),
                ('crew_5', models.CharField(max_length=60)),
                ('crew_5_desc', models.CharField(max_length=60)),
                ('crew_5_img', models.FileField(upload_to='file')),
            ],
        ),
    ]
