# Generated by Django 5.2.8 on 2025-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0015_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movie',
            name='movie_poster',
            field=models.FileField(default='', upload_to='file'),
        ),
    ]
