# Generated by Django 5.2.8 on 2025-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0016_add_movie_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movie',
            name='format',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='lang',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
