# Generated by Django 5.2.8 on 2025-11-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0017_add_movie_format_add_movie_genre_add_movie_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movie',
            name='certificate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='votes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
