# Generated by Django 5.2.8 on 2025-12-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0018_add_movie_certificate_add_movie_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='the',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=100)),
            ],
        ),
    ]
