# Generated by Django 5.2.8 on 2025-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0019_the'),
    ]

    operations = [
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.CharField(max_length=100)),
                ('show_day', models.CharField(max_length=100)),
            ],
        ),
    ]
