# Generated by Django 5.2.8 on 2025-12-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0020_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='up_coming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_movie', models.CharField(max_length=100)),
                ('poster', models.FileField(upload_to='file')),
            ],
        ),
    ]
