# Generated by Django 5.2.8 on 2025-12-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0021_up_coming'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='movie_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
