# Generated by Django 5.2.8 on 2025-12-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0022_crew_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movie',
            name='date_from',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='add_movie',
            name='date_to',
            field=models.CharField(default='', max_length=50),
        ),
    ]
