# Generated by Django 5.2.8 on 2025-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0023_add_movie_date_from_add_movie_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_movie',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
