# Generated by Django 5.2.8 on 2025-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0024_alter_add_movie_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seat_rates',
        ),
        migrations.AddField(
            model_name='seats',
            name='number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
