# Generated by Django 5.2.8 on 2025-12-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0025_delete_seat_rates_seats_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='theatre_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
