# Generated by Django 5.2.8 on 2025-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0026_seats_theatre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatres',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
