# Generated by Django 5.2.8 on 2025-12-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0028_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='number',
        ),
    ]
