# Generated by Django 5.2.8 on 2026-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0029_remove_register_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_movie_name', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=50)),
                ('votes', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
