# Generated by Django 5.2.8 on 2026-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0030_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='cast1',
            field=models.FileField(default='', upload_to='file'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='cast2',
            field=models.FileField(default='', upload_to='file'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='cast3',
            field=models.FileField(default='', upload_to='file'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='cast4',
            field=models.FileField(default='', upload_to='file'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='poster',
            field=models.FileField(default='', upload_to='file'),
        ),
    ]
