# Generated by Django 5.2.8 on 2026-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0031_highlight_cast1_highlight_cast2_highlight_cast3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('u_type', models.CharField(max_length=100)),
            ],
        ),
    ]
