# Generated by Django 5.2.8 on 2026-01-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0032_login_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('acc_no', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=10)),
            ],
        ),
    ]
