# Generated by Django 5.2.8 on 2026-01-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0033_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='balance',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
