# Generated by Django 5.2.8 on 2026-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0034_verify_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='balance',
            field=models.CharField(max_length=100),
        ),
    ]
