# Generated by Django 5.2.8 on 2026-01-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0035_alter_verify_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('movie', models.CharField(max_length=100)),
                ('theatre', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('seats', models.CharField(max_length=100)),
                ('seat_count', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
