# Generated by Django 5.2.8 on 2026-01-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0038_bookedseat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedSeat',
        ),
    ]
