# Generated by Django 5.2.8 on 2026-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0039_delete_bookedseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
