# Generated by Django 5.2.8 on 2026-01-16 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0041_bookedseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
